### ISSUE TITLE
Formato do nome da pasta de reunião

### ISSUE THREAD

**Issue by gbrlwbr** [Trans-Formacao/Reunioes#2]
@vikttu, não deveríamos nomeá-las ao contrário: `R_aa-mm-dd/Pauta.md`, para que assim o ordenamento fique naturalmente por ano > mês > dia ?

**Comment by vikttu** [comment]
então, coloquei como dd-mm-aa pq é o jeito que a gente usa a data, né, mas pq q aa-mm-dd seria melhor?

**Comment by gbrlwbr** [comment]
Na hora de ordenar lexograficamente, com o seu formato vamos agrupar todas
as reuniões ocorridas no mesmo dia,  com o meu formato,  todas no mesmo
ano.

**Comment by vikttu** [comment]
hmmm realmente, vou mudar
